apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-volume
  labels:
    app: nginx-app-demo
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/"