apiVersion: v1
kind: Service
metadata:
  name: nginx-app-demo
  labels:
    app: nginx-app-demo
spec:
  # type: NodePort
  selector:
    app: nginx-app-demo
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      # nodePort: 30080